============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-8.3.2, pluggy-1.5.0 -- /home/yasnoz/.pyenv/versions/3.10.6/envs/taxifare-env/bin/python
cachedir: .pytest_cache
rootdir: /home/yasnoz/code/yasnoz/07-ML-Ops/04-Predict-in-production/data-fast-api/tests
configfile: pytest_kitt.ini
plugins: anyio-3.7.1, asyncio-0.24.0
asyncio: mode=strict, default_loop_scope=None
collecting ... collected 18 items

tests/api/test_cloud_endpoints.py::test_root_is_up FAILED                [  5%]
tests/api/test_cloud_endpoints.py::test_root_returns_greeting FAILED     [ 11%]
tests/api/test_cloud_endpoints.py::test_predict_is_up FAILED             [ 16%]
tests/api/test_cloud_endpoints.py::test_predict_is_dict FAILED           [ 22%]
tests/api/test_cloud_endpoints.py::test_predict_has_key FAILED           [ 27%]
tests/api/test_cloud_endpoints.py::test_cloud_api_predict FAILED         [ 33%]
tests/api/test_docker_endpoints.py::test_root_is_up PASSED               [ 38%]
tests/api/test_docker_endpoints.py::test_root_returns_greeting PASSED    [ 44%]
tests/api/test_docker_endpoints.py::test_predict_is_up PASSED            [ 50%]
tests/api/test_docker_endpoints.py::test_predict_is_dict PASSED          [ 55%]
tests/api/test_docker_endpoints.py::test_predict_has_key PASSED          [ 61%]
tests/api/test_docker_endpoints.py::test_cloud_api_predict PASSED        [ 66%]
tests/api/test_endpoints.py::test_root_is_up PASSED                      [ 72%]
tests/api/test_endpoints.py::test_root_returns_greeting PASSED           [ 77%]
tests/api/test_endpoints.py::test_predict_is_up PASSED                   [ 83%]
tests/api/test_endpoints.py::test_predict_is_dict PASSED                 [ 88%]
tests/api/test_endpoints.py::test_predict_has_key PASSED                 [ 94%]
tests/api/test_endpoints.py::test_predict_val_is_float PASSED            [100%]

=================================== FAILURES ===================================
_______________________________ test_root_is_up ________________________________

    @pytest.mark.asyncio
    async def test_root_is_up():
>       assert SERVICE_URL # Stop if env variable SERVICE_URL is not set
E       assert None

tests/api/test_cloud_endpoints.py:30: AssertionError
__________________________ test_root_returns_greeting __________________________

    @pytest.mark.asyncio
    async def test_root_returns_greeting():
>       assert SERVICE_URL # Stop if env variable SERVICE_URL is not set
E       assert None

tests/api/test_cloud_endpoints.py:38: AssertionError
______________________________ test_predict_is_up ______________________________

    @pytest.mark.asyncio
    async def test_predict_is_up():
>       assert SERVICE_URL # Stop if env variable SERVICE_URL is not set
E       assert None

tests/api/test_cloud_endpoints.py:46: AssertionError
_____________________________ test_predict_is_dict _____________________________

    @pytest.mark.asyncio
    async def test_predict_is_dict():
>       assert SERVICE_URL # Stop if env variable SERVICE_URL is not set
E       assert None

tests/api/test_cloud_endpoints.py:54: AssertionError
_____________________________ test_predict_has_key _____________________________

    @pytest.mark.asyncio
    async def test_predict_has_key():
>       assert SERVICE_URL # Stop if env variable SERVICE_URL is not set
E       assert None

tests/api/test_cloud_endpoints.py:63: AssertionError
____________________________ test_cloud_api_predict ____________________________

    @pytest.mark.asyncio
    async def test_cloud_api_predict():
>       assert SERVICE_URL # Stop if env variable SERVICE_URL is not set
E       assert None

tests/api/test_cloud_endpoints.py:70: AssertionError
=========================== short test summary info ============================
FAILED tests/api/test_cloud_endpoints.py::test_root_is_up - assert None
FAILED tests/api/test_cloud_endpoints.py::test_root_returns_greeting - assert...
FAILED tests/api/test_cloud_endpoints.py::test_predict_is_up - assert None
FAILED tests/api/test_cloud_endpoints.py::test_predict_is_dict - assert None
FAILED tests/api/test_cloud_endpoints.py::test_predict_has_key - assert None
FAILED tests/api/test_cloud_endpoints.py::test_cloud_api_predict - assert None
================== 6 failed, 12 passed, 9 warnings in 27.20s ===================
